# Generated by Django 2.1.15 on 2020-07-02 06:04

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliography',
            name='year',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='church',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='church',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='church',
            name='external_link',
            field=models.URLField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='church',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326),
        ),
    ]
