# Generated by Django 2.1.15 on 2020-07-03 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saints', '0002_auto_20200702_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='coordinates',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='saints.Location'),
        ),
    ]
